### PR TITLE
Switch from get_cache to caches

### PR DESCRIPTION
**Pull request by ebrelsford**
get_cache is deprecated and will be removed in Django 1.9

### CODE REVIEW

**Comment by tobiasmcnulty** [comment]
Closing and re-opening this PR to force a build on Travis.

**Comment by tobiasmcnulty** [comment]
Hi @ebrelsford, many thanks for this. Could you add the appropriate conditions to get this working pre-1.7?

For an example see: https://github.com/django-cache-machine/django-cache-machine/blob/master/caching/compat.py#L6

Thanks!

**Comment by ebrelsford** [comment]
Good point, done.

**Comment by tobiasmcnulty** [comment]
Forcing another re-build since I just added tests under 1.8.

**Pull request merged**
